/**
 * Email Draft Types for Luframe Frontend
 *
 * These types match the backend schemas/email_draft.py and are used
 * for real-time email draft generation and display.
 *
 * Email drafts are generated when ActionClassifier identifies email-type actions
 * and EmailDraftGenerator creates AI-generated drafts for user review.
 */

// ============================================================================
// Constants
// ============================================================================

/**
 * Maximum number of email drafts to keep in memory.
 */
export const MAX_DRAFTS = 50;

/**
 * Confidence threshold for displaying low-confidence indicators.
 */
export const DRAFT_CONFIDENCE_THRESHOLD = 0.6;

/**
 * Default confidence value when not provided.
 */
export const DEFAULT_DRAFT_CONFIDENCE = 0.8;

// ============================================================================
// Types
// ============================================================================

/**
 * Status of an email draft in its lifecycle.
 * Matches DraftStatus enum from backend.
 */
export type DraftStatus =
  | "generating" // Draft is being generated by LLM
  | "ready" // Draft is ready for user review
  | "edited" // User has edited the draft
  | "sent" // Email has been sent
  | "rejected" // User rejected the draft
  | "failed"; // Generation failed

/**
 * All valid draft statuses for validation.
 */
export const VALID_DRAFT_STATUSES: DraftStatus[] = [
  "generating",
  "ready",
  "edited",
  "sent",
  "rejected",
  "failed",
];

/**
 * Email recipient with optional metadata.
 * Matches EmailRecipient from backend.
 */
export interface EmailRecipient {
  /** Email address if known (from participant list) */
  email: string | null;
  /** Name or role of the recipient */
  name: string;
  /** How recipient was determined: 'inferred', 'explicit', 'participant' */
  source: "inferred" | "explicit" | "participant";
}

/**
 * Meeting context information for email generation.
 * Provides relevant meeting details for contextually appropriate drafts.
 */
export interface MeetingContext {
  /** Title of the meeting */
  meetingTitle: string | null;
  /** Date of the meeting (ISO format or human readable) */
  meetingDate: string | null;
  /** List of participant names in the meeting */
  participants: string[];
  /** Agenda topics being discussed */
  agendaTopics: string[];
  /** Room identifier for meeting links */
  roomId: string | null;
}

/**
 * Default meeting context values.
 */
export const DEFAULT_MEETING_CONTEXT: MeetingContext = {
  meetingTitle: null,
  meetingDate: null,
  participants: [],
  agendaTopics: [],
  roomId: null,
};

/**
 * An AI-generated email draft from a meeting action item.
 * Matches EmailDraft from backend (camelCase).
 */
export interface EmailDraft {
  /** Unique draft identifier */
  id: string;

  // Link to source action and meeting
  /** ID of the ClassifiedAction that triggered this draft */
  actionId: string;
  /** ID of the original action_item insight */
  originalInsightId: string;
  /** ID of the meeting this draft belongs to (for audit logging) */
  meetingId: string;
  /** Room ID for quick access */
  roomId: string;

  // Email content
  /** Suggested email recipients */
  suggestedTo: EmailRecipient[];
  /** Email subject line */
  subject: string;
  /** Email body content */
  body: string;

  // Context that generated this draft
  /** Meeting context used for generation */
  meetingContext: MeetingContext;
  /** Transcript excerpt used for generation */
  transcriptContext: string | null;

  // Source action data (copied for convenience)
  /** Original action item content */
  actionContent: string;
  /** Type of email action (email_followup, email_share, email_schedule) */
  actionType: string;
  /** Name of person who mentioned the action */
  speakerName: string | null;

  // Draft metadata
  /** Current status of the draft */
  status: DraftStatus;
  /** Confidence in draft quality (0.0-1.0) */
  generationConfidence: number;

  // Timestamps
  /** When the draft was generated (ms) */
  generatedAt: number;

  // Error tracking (for failed status)
  /** Error message if generation failed */
  errorMessage: string | null;
}

/**
 * User edits to an email draft before sending.
 */
export interface EmailDraftEdits {
  /** Edited recipients */
  to?: string[];
  /** Edited CC recipients */
  cc?: string[];
  /** Edited subject line */
  subject?: string;
  /** Edited body content */
  body?: string;
}

/**
 * Full email data ready for sending (draft + edits).
 */
export interface EmailToSend {
  /** Draft ID for reference */
  draftId: string;
  /** Meeting ID for audit trail */
  meetingId?: string;
  /** Final recipients (email addresses) */
  to: string[];
  /** CC recipients */
  cc?: string[];
  /** Final subject line */
  subject: string;
  /** Final body content */
  body: string;
}

// ============================================================================
// Status Configuration
// ============================================================================

/**
 * Configuration for each draft status including display properties.
 */
export interface DraftStatusConfig {
  /** Human-readable label */
  label: string;
  /** Short description */
  description: string;
  /** Text color class */
  color: string;
  /** Background color class */
  bgColor: string;
  /** Whether the draft is actionable (can be edited/sent) */
  actionable: boolean;
}

/**
 * Configuration mapping for all draft statuses.
 */
export const DRAFT_STATUS_CONFIG: Record<DraftStatus, DraftStatusConfig> = {
  generating: {
    label: "Generating",
    description: "AI is generating the draft...",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-50 dark:bg-amber-950/50",
    actionable: false,
  },
  ready: {
    label: "Ready",
    description: "Draft ready for review",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-50 dark:bg-green-950/50",
    actionable: true,
  },
  edited: {
    label: "Edited",
    description: "You've made changes",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/50",
    actionable: true,
  },
  sent: {
    label: "Sent",
    description: "Email has been sent",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
    actionable: false,
  },
  rejected: {
    label: "Dismissed",
    description: "Draft was dismissed",
    color: "text-gray-500 dark:text-gray-400",
    bgColor: "bg-gray-50 dark:bg-gray-950/50",
    actionable: false,
  },
  failed: {
    label: "Failed",
    description: "Generation failed",
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-50 dark:bg-red-950/50",
    actionable: false,
  },
};

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Parse draft status from string, with fallback to generating.
 */
export function parseDraftStatus(
  value: string | undefined | null
): DraftStatus {
  if (!value) return "generating";
  const normalized = value.toLowerCase().trim();
  return VALID_DRAFT_STATUSES.includes(normalized as DraftStatus)
    ? (normalized as DraftStatus)
    : "generating";
}

/**
 * Normalize timestamp to milliseconds.
 * Handles both seconds and milliseconds from the agent.
 */
export function normalizeDraftTimestamp(
  ts: number | undefined | null
): number {
  if (ts === undefined || ts === null || ts === 0) {
    return Date.now();
  }
  // If timestamp is less than 1e12, it's in seconds
  return ts < 1e12 ? ts * 1000 : ts;
}

/**
 * Normalize confidence from integer (0-100) to float (0.0-1.0).
 */
export function normalizeDraftConfidence(
  value: number | undefined | null
): number {
  if (value === undefined || value === null) {
    return DEFAULT_DRAFT_CONFIDENCE;
  }
  // If value is > 1, assume it's a percentage
  if (value > 1) {
    return value / 100;
  }
  return value;
}

/**
 * Format timestamp for display (HH:MM format).
 */
export function formatDraftTime(timestamp: number): string {
  return new Date(timestamp).toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });
}

/**
 * Check if a draft can be edited.
 */
export function isDraftEditable(status: DraftStatus): boolean {
  return status === "ready" || status === "edited";
}

/**
 * Check if a draft can be sent.
 */
export function isDraftSendable(status: DraftStatus): boolean {
  return status === "ready" || status === "edited";
}

/**
 * Get initials from a name for avatar display.
 */
export function getRecipientInitials(name: string): string {
  return name
    .split(" ")
    .map((part) => part[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

/**
 * Format recipients list for display.
 */
export function formatRecipients(recipients: EmailRecipient[]): string {
  if (recipients.length === 0) return "No recipients";
  if (recipients.length === 1) {
    return recipients[0].email || recipients[0].name;
  }
  return `${recipients[0].email || recipients[0].name} +${recipients.length - 1}`;
}

/**
 * Truncate text to a maximum length with ellipsis.
 */
export function truncateText(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + "...";
}

/**
 * Parse email recipients from agent data.
 */
export function parseEmailRecipients(
  data: unknown
): EmailRecipient[] {
  if (!Array.isArray(data)) return [];

  return data
    .filter((item): item is Record<string, unknown> =>
      item !== null && typeof item === "object"
    )
    .map((item) => ({
      email: typeof item.email === "string" ? item.email : null,
      name: typeof item.name === "string" ? item.name : "Unknown",
      source: (["inferred", "explicit", "participant"].includes(item.source as string)
        ? item.source
        : "inferred") as EmailRecipient["source"],
    }));
}

/**
 * Parse meeting context from agent data.
 */
export function parseMeetingContext(
  data: unknown
): MeetingContext {
  if (!data || typeof data !== "object") {
    return DEFAULT_MEETING_CONTEXT;
  }

  const ctx = data as Record<string, unknown>;

  return {
    meetingTitle: typeof ctx.meetingTitle === "string" ? ctx.meetingTitle : null,
    meetingDate: typeof ctx.meetingDate === "string" ? ctx.meetingDate : null,
    participants: Array.isArray(ctx.participants)
      ? ctx.participants.filter((p): p is string => typeof p === "string")
      : [],
    agendaTopics: Array.isArray(ctx.agendaTopics)
      ? ctx.agendaTopics.filter((t): t is string => typeof t === "string")
      : [],
    roomId: typeof ctx.roomId === "string" ? ctx.roomId : null,
  };
}

/**
 * Validate that a string is non-empty after trimming.
 */
export function isNonEmptyDraftString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}
